title: Саратовский центр СПО
email: info@sarfsc.ru
description: >-
  Саратовский центр развития свободного программного обеспечения
baseurl: ""
url: "http://sarfsc.ru"
twitter_username: SaratovFreeSoft
github_username: sarfsc
host: tor
encode: utf8

show_downloads: "true" # to indicate whether to provide a download URL]
#google_analytics: [Your Google Analytics tracking ID]

# Build settings
markdown: kramdown

# https://github.com/jekyll/minima
theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag
